package com.wex.purchases.purchase;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Stored purchase transaction. The amount is always recorded in United States dollars,
 * persisted with scale=2 (cents). The unique identifier is generated by the service
 * layer at creation time so it can be returned in the API response.
 */
@Entity
@Table(name = "purchases")
public class Purchase {

    @Id
    @Column(name = "id", nullable = false, updatable = false, columnDefinition = "uuid")
    private UUID id;

    @Column(name = "description", nullable = false, length = 50)
    private String description;

    @Column(name = "transaction_date", nullable = false)
    private LocalDate transactionDate;

    @Column(name = "purchase_amount_usd", nullable = false, precision = 19, scale = 2)
    private BigDecimal purchaseAmountUsd;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected Purchase() {
        // JPA
    }

    public Purchase(UUID id, String description, LocalDate transactionDate, BigDecimal purchaseAmountUsd) {
        this.id = id;
        this.description = description;
        this.transactionDate = transactionDate;
        this.purchaseAmountUsd = purchaseAmountUsd;
    }

    public UUID getId() {
        return id;
    }

    public String getDescription() {
        return description;
    }

    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    public BigDecimal getPurchaseAmountUsd() {
        return purchaseAmountUsd;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
